# Use Ubuntu as base image
FROM ubuntu:latest

# Prevent prompts during installation
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && \
    apt-get install -y curl git && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs

# Clone React project
RUN git clone https://github.com/vitejs/vite.git

# Move into React template
WORKDIR /vite/packages/create-vite/template-react

# Install dependencies
RUN npm install

# Expose Vite port
EXPOSE 5173

# Start application
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]